#!/bin/zsh

project="$HOME/wd/workflow/json"
mkdir -p "$project"
timestamp=$(date +%s)
file="${project}/${timestamp}.json"
pbpaste | python3 -m json.tool --indent 2 &> "$file"
/usr/local/bin/code "$project"
/usr/local/bin/code -r "$file"
